# Generated by Django 6.0.5 on 2026-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
